build_dependencies:
  - mongodb-server
dependencies:
  - mongodb-org-server (= 3.4.5)
before:
  - mkdir -p /tmp/db
  - /usr/bin/mongod --dbpath /tmp/db --fork --syslog
after_install: "contrib/scripts/after_install.sh"
targets:
  ubuntu-16.04:
