build_dependencies:
  - mongodb-server
dependencies:
  - mongodb-org-server (= 4.0.18)
  - libcurl4
before:
  - mkdir -p /tmp/db
  - /usr/bin/mongod --dbpath /tmp/db --fork --syslog
targets:
  ubuntu-16.04:
  ubuntu-18.04:
