inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  RubyInterpreters:
    - ruby
    - macruby
    - rake
    - jruby
    - rbx
  # Include common Ruby source files.
  Exclude:
      - bin/*
      - db/schema.rb
      - db/migrate/*
      - config/initializers/*
      - 'vendor/**/*'
      - 'lib/tasks/cucumber.rake'
  NewCops: enable
  TargetRubyVersion: 2.7
Layout/LineLength:
  Max: 150
  Exclude:
    - 'app/controllers/products_controller.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/cypress/demographics_randomizer.rb'
    - 'lib/validators/program_criteria_validator.rb'
    - 'test/**/*'
Lint/UnreachableLoop:
  Exclude:
    - 'test/unit/lib/record_filter_test.rb'    
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or
  # a Float.
  Max: 32
  Exclude:
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/test_executions_controller.rb'
    - 'app/models/cms_program_task.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/cypress/population_clone_job.rb'
    - 'test/**/*.rb'
    - 'lib/validators/program_criteria_validator.rb'
Metrics/BlockLength:
  Max: 38
  Exclude:
    - 'app/controllers/products_controller.rb'
    - 'config/routes.rb'
    - 'test/factories/*'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/tasks/*'
Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'test/**/*'
    - 'app/controllers/products_controller.rb'
    - 'app/models/product.rb'
    - 'app/models/checklist_source_data_criteria.rb'
    - 'app/models/settings.rb'
    - 'app/controllers/records_controller.rb'
    - 'lib/ext/patient.rb'
    - 'lib/cypress/api_measure_evaluator.rb'
    - 'lib/cypress/clinical_randomizer.rb'
    - 'lib/cypress/cql_bundle_importer.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/cypress/demographics_randomizer.rb'
    - 'lib/cypress/expected_results_calculator.rb'
    - 'lib/cypress/population_clone_job.rb'
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20
  Exclude:
    - 'app/controllers/products_controller.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'test/**/*'
Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'app/helpers/patient_analysis_helper.rb'
Metrics/ParameterLists:
  Exclude:
    - 'app/helpers/records_helper.rb'
    - 'app/jobs/cms_test_execution_job.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/validators/expected_results_validator.rb'
Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'app/controllers/products_controller.rb'
    - 'app/helpers/products_helper.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/validators/checklist_criteria_validator.rb'
    - 'test/unit/lib/validators/checklist_criteria_validator_test.rb'
    - 'test/unit/html_test.rb'
Style/CaseLikeIf:
  Exclude:
    - 'app/controllers/test_executions_controller.rb'
    - 'app/jobs/measure_evaluation_job.rb'