# Below are Cops that return errors that had not be caught by ~v0.66.0
# TODO: fix, or intentionally Exclude them 
Lint/MissingSuper:
  Exclude:
Naming/MethodParameterName:
  Exclude:
Naming/RescuedExceptionsVariableName:
  Exclude:
Naming/VariableName:
  Exclude:
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or
  # a Float.
  Exclude:
Metrics/CyclomaticComplexity:
  Exclude:
Metrics/PerceivedComplexity:
  Exclude:
Style/AccessorGrouping:
  Exclude:
Style/CaseLikeIf:
  Exclude:
Style/CombinableLoops:
  Exclude:
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Exclude:
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Exclude:
Style/HashLikeCase:
  Exclude:
Style/HashEachMethods:
  Exclude:
Style/IfUnlessModifier:
  Exclude:
Style/MixinUsage:
  Exclude:
Style/RedundantReturn:
  Exclude:
Style/GlobalStdStream:
  Exclude:
Style/OptionalBooleanParameter:
  Exclude:
    - 'app/helpers/checklist_tests_helper.rb'
    - 'app/helpers/products_helper.rb'
    - 'app/models/product.rb'
    - 'lib/cypress/cql_bundle_importer.rb'
    - 'lib/cypress/cqm_execution_calc.rb'
    - 'lib/cypress/demographics_randomizer.rb'
    - 'lib/cypress/error_collector.rb'
    - 'lib/cypress/expected_results_calculator.rb'
    - 'lib/cypress/population_clone_job.rb'
    - 'lib/ext/individual_result.rb'
    - 'lib/validators/cms_schematron_validator.rb'
    - 'lib/validators/validator.rb'
    - 'test/helpers/products_helper_test.rb'
    - 'test/test_helper.rb'
    - 'test/unit/product_report_test.rb'
Style/RedundantAssignment:
  Exclude:
Style/RedundantFileExtensionInRequire:
  Exclude:
Style/RedundantRegexpCharacterClass:
  Exclude:
Style/RedundantRegexpEscape:
  Exclude:
Style/RedundantParentheses:
  Exclude:
Style/RescueStandardError:
  Exclude:
Style/SafeNavigation:
  Exclude:
Style/SoleNestedConditional:
  Exclude:
Style/StringConcatenation:
  Exclude:
Style/StringLiterals:
  Exclude:
Style/WordArray:
  Exclude:
