# Below are Cops that return errors that had not be caught by ~v0.66.0
# TODO: fix, or intentionally Exclude them 
Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'test/helpers/products_helper_test.rb'
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/tasks_controller.rb'
Lint/FloatComparison:
  Exclude:
    - 'lib/validators/expected_results_validator.rb'
Lint/MissingSuper:
  Exclude:
    - 'lib/cypress/highlighting/highlighting.rb'
    - 'lib/validators/cat3_population_validator.rb'
    - 'lib/validators/checklist_criteria_validator.rb'
    - 'lib/validators/cms_schematron_validator.rb'
    - 'lib/validators/core_clinical_data_element_validator.rb'
    - 'lib/validators/ehr_certification_id_validator.rb'
    - 'lib/validators/encounter_validator.rb'
    - 'lib/validators/expected_results_validator.rb'
    - 'lib/validators/measure_period_validator.rb'
    - 'lib/validators/program_criteria_validator.rb'
    - 'lib/validators/program_validator.rb'
    - 'lib/validators/provider_type_validator.rb'
    - 'lib/validators/qrda_cat1_validator.rb'
    - 'lib/validators/qrda_cat3_validator.rb'
    - 'lib/validators/qrda_upload_validator.rb'
Lint/NonDeterministicRequireOrder:
  Exclude:
    - 'lib/cypress.rb'
Layout/TrailingEmptyLines:
  Exclude:
    - '.simplecov'
Lint/RedundantCopDisableDirective:
  Exclude:
    - 'lib/cypress/expected_results_calculator.rb'
    - 'app/controllers/records_controller.rb'
Lint/RedundantStringCoercion:
  Exclude:
    - 'app/models/product_test.rb'
Lint/SuppressedException:
  Exclude:
    - 'app/models/point_of_contact.rb'
Lint/UnreachableLoop:
  Exclude:
    - 'test/unit/lib/record_filter_test.rb'
Lint/UselessMethodDefinition:
  Exclude:
    - 'app/controllers/registrations_controller.rb'
Naming/MethodParameterName:
  Exclude:
    - 'app/helpers/checklist_tests_helper.rb'
    - 'app/helpers/patient_analysis_helper.rb'
    - 'app/helpers/test_executions_results_helper.rb'
    - 'app/jobs/cms_test_execution_job.rb'
    - 'app/jobs/test_execution_job.rb'
    - 'app/models/test_execution.rb'
    - 'lib/cypress/api_measure_evaluator.rb'
    - 'lib/cypress/clinical_randomizer.rb'
    - 'lib/cypress/create_download_zip.rb'
    - 'lib/cypress/create_total_test_zip.rb'
    - 'lib/cypress/highlighting/highlighting.rb'
    - 'lib/cypress/measure_evaluator.rb'
    - 'lib/cypress/patient_filter.rb'
    - 'test/helpers/products_helper_test.rb'
    - 'test/helpers/test_executions_helper_test.rb'
    - 'test/helpers/test_executions_helper_test.rb'
    - 'test/models/patient_test.rb'
    - 'test/test_helper.rb'
Naming/RescuedExceptionsVariableName:
  Exclude:
    - 'lib/validators/encounter_validator.rb'
Naming/VariableName:
  Exclude:
    - 'app/controllers/sessions_controller.rb'
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or
  # a Float.
  Exclude:
    - 'app/controllers/records_controller.rb'
    - 'app/helpers/patient_analysis_helper.rb'
    - 'lib/cypress/cql_bundle_importer.rb'
    - 'lib/cypress/demographics_randomizer.rb'
    - 'lib/cypress/expected_results_calculator.rb'
    - 'lib/cypress/product_status_values.rb'
    - 'lib/ext/individual_result.rb'
    - 'lib/ext/patient.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/records_controller.rb'
    - 'app/helpers/filtering_tests_helper.rb'
    - 'app/helpers/products_helper.rb'
    - 'app/helpers/test_executions_helper.rb'
    - 'app/models/ability.rb'
    - 'app/models/c1_task.rb'
    - 'app/models/c2_task.rb'
    - 'app/models/cat3_filter_task.rb'
    - 'app/models/measure_test.rb'
    - 'app/models/product.rb'
    - 'app/models/product.rb'
    - 'app/models/product_test.rb'
    - 'app/models/test_execution.rb'
    - 'lib/cypress/api_measure_evaluator.rb'
    - 'lib/cypress/clinical_randomizer.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/cypress/data_criteria_selector.rb'
    - 'lib/cypress/expected_results_calculator.rb'
    - 'lib/cypress/highlighting/highlighting.rb'
    - 'lib/cypress/patient_filter.rb'
    - 'lib/cypress/patient_zipper.rb'
    - 'lib/cypress/population_clone_job.rb'
    - 'lib/cypress/product_status_values.rb'
    - 'lib/cypress/qrda_post_processor.rb'
    - 'lib/ext/individual_result.rb'
    - 'lib/ext/patient.rb'
    - 'lib/tasks/bundle_eval.rake'
    - 'lib/validators/calculating_augmented_records.rb'
    - 'lib/validators/calculating_augmented_results.rb'
    - 'lib/validators/cat3_population_validator.rb'
    - 'lib/validators/checklist_criteria_validator.rb'
    - 'lib/validators/expected_results_validator.rb'
    - 'test/integration/api_measure_evaluator_test.rb'
    - 'test/test_helper.rb'
    - 'test/unit/html_test.rb'
    - 'test/unit/lib/provider_filter_test.rb'
    - 'test/unit/lib/validators/checklist_criteria_validator_test.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/product.rb'
    - 'lib/cypress/expected_results_calculator.rb'
    - 'lib/cypress/highlighting/highlighting.rb'
    - 'lib/cypress/patient_filter.rb'
    - 'lib/cypress/patient_zipper.rb'
    - 'lib/cypress/qrda_post_processor.rb'
    - 'lib/ext/individual_result.rb'
    - 'lib/validators/expected_results_validator.rb'
    - 'test/integration/api_measure_evaluator_test.rb'
Style/AccessorGrouping:
  Exclude:
    - 'lib/cypress/patient_zipper.rb'
Style/CaseLikeIf:
  Exclude:
    - 'app/controllers/admin/settings_controller.rb'
    - 'app/controllers/test_executions_controller.rb'
    - 'app/jobs/measure_evaluation_job.rb'
    - 'lib/cypress/api_measure_evaluator.rb'
    - 'lib/cypress/create_download_zip.rb'
    - 'lib/validators/qrda_upload_validator.rb'
Style/ClassAndModuleChildren:
  Exclude:
    - '.simplecov'
    - 'test/test_helper.rb'
Style/CombinableLoops:
  Exclude:
    - 'test/integration/api_measure_evaluator_test.rb'
    - 'test/models/checklist_test_test.rb'
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Exclude:
    - 'config.ru'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Exclude:
    - 'app/controllers/admin/users_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/records_controller.rb'
    - 'app/helpers/checklist_tests_helper.rb'
    - 'app/jobs/cms_test_execution_job.rb'
    - 'app/models/c3_cat3_task.rb'
    - 'app/models/checklist_source_data_criteria.rb'
    - 'app/models/point_of_contact.rb'
    - 'app/models/product.rb'
    - 'app/models/settings.rb'
    - 'app/models/user.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/cypress/demographics_randomizer.rb'
    - 'lib/ext/bundle.rb'
    - 'lib/ext/individual_result.rb'
    - 'lib/ext/patient.rb'
    - 'lib/validators/cat3_population_validator.rb'
    - 'lib/validators/cms_schematron_validator.rb'
    - 'lib/validators/ehr_certification_id_validator.rb'
    - 'lib/validators/expected_supplemental_results.rb'
    - 'lib/validators/measure_period_validator.rb'
    - 'lib/validators/program_criteria_validator.rb'
    - 'lib/validators/provider_type_validator.rb'
    - 'lib/validators/qrda_cat3_validator.rb'
    - 'lib/validators/qrda_upload_validator.rb'
    - 'lib/validators/qrda_upload_validator.rb'
    - 'test/api_test.rb'
Style/HashLikeCase:
  Exclude:
    - 'features/step_definitions/checklist_test.rb'
    - 'features/step_definitions/product.rb'
Style/HashEachMethods:
  Exclude:
    - 'app/controllers/products_controller.rb'
    - 'lib/cypress/expected_results_calculator.rb'
Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/products_controller.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/cypress/demographics_randomizer.rb'
    - 'test/integration/api_measure_evaluator_test.rb'
    - 'test/unit/lib/validators/checklist_criteria_validator_test.rb'
Style/MixinUsage:
  Exclude:
    - 'features/step_definitions/checklist_test.rb'
    - 'features/step_definitions/filtering_test.rb'
    - 'features/step_definitions/measure_test.rb'
    - 'features/step_definitions/multi_measure_test.rb'
    - 'features/step_definitions/product.rb'
    - 'features/step_definitions/program_test.rb'
    - 'features/step_definitions/record.rb'
    - 'features/step_definitions/record_list.rb'
    - 'test/test_helper.rb'
Style/RedundantReturn:
  Exclude:
    - 'app/helpers/products_helper.rb'
    - 'app/jobs/vendor_patient_upload_job.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'
    - 'lib/cypress/cql_bundle_importer.rb'
Style/OptionalBooleanParameter:
  Exclude:
    - 'app/helpers/checklist_tests_helper.rb'
    - 'app/helpers/products_helper.rb'
    - 'app/models/product.rb'
    - 'lib/cypress/cql_bundle_importer.rb'
    - 'lib/cypress/cqm_execution_calc.rb'
    - 'lib/cypress/demographics_randomizer.rb'
    - 'lib/cypress/error_collector.rb'
    - 'lib/cypress/expected_results_calculator.rb'
    - 'lib/cypress/population_clone_job.rb'
    - 'lib/ext/individual_result.rb'
    - 'lib/validators/cms_schematron_validator.rb'
    - 'lib/validators/validator.rb'
    - 'test/helpers/products_helper_test.rb'
    - 'test/test_helper.rb'
    - 'test/unit/product_report_test.rb'
Style/RedundantAssignment:
  Exclude:
    - 'app/jobs/measure_evaluation_job.rb'
    - 'app/jobs/product_test_setup_job.rb'
    - 'lib/cypress/cqm_execution_calc.rb'
    - 'lib/validators/calculating_augmented_records.rb'
    - 'lib/validators/calculating_smoking_gun_validator.rb'
Style/RedundantFileExtensionInRequire:
  Exclude:
    - 'lib/cypress.rb'
    - 'test/integration/api_measure_evaluator_test.rb'
    - 'test/unit/default_provider_test.rb'
    - 'test/unit/html_test.rb'
Style/RedundantRegexpCharacterClass:
  Exclude:
    - 'app/models/user.rb'
Style/RedundantRegexpEscape:
  Exclude:
    - 'features/step_definitions/record.rb'
    - 'lib/cypress/cql_bundle_importer.rb'
Style/RedundantParentheses:
  Exclude:
    - 'app/models/test_execution.rb'
Style/RescueStandardError:
  Exclude:
    - 'app/controllers/sessions_controller.rb'
    - 'app/controllers/tasks_controller.rb'
    - 'app/helpers/test_executions_helper.rb'
    - 'app/jobs/vendor_patient_upload_job.rb'
    - 'app/lib/job/status.rb'
    - 'app/models/filtering_test.rb'
    - 'app/models/point_of_contact.rb'
    - 'app/models/task.rb'
    - 'app/models/test_execution.rb'
    - 'lib/cypress/api_measure_evaluator.rb'
    - 'lib/cypress/cql_bundle_importer.rb'
    - 'lib/cypress/cqm_execution_calc.rb'
    - 'lib/cypress/data_criteria_attribute_builder.rb'
    - 'lib/cypress/error_collector.rb'
    - 'lib/cypress/product_status_values.rb'
    - 'lib/ext/bundle.rb'
    - 'lib/validators/calculating_augmented_records.rb'
    - 'lib/validators/calculating_smoking_gun_validator.rb'
Style/SafeNavigation:
  Exclude:
    - 'app/models/checklist_test.rb'
Style/SoleNestedConditional:
  Exclude:
    - 'app/helpers/checklist_tests_helper.rb'
Style/StringConcatenation:
  Exclude:
    - 'app/controllers/checklist_tests_controller.rb'
    - 'app/controllers/products_controller.rb'
    - 'app/controllers/program_tests_controller.rb'
    - 'app/controllers/records_controller.rb'
    - 'app/controllers/test_executions_controller.rb'
    - 'app/controllers/vendors_controller.rb'
    - 'app/helpers/checklist_tests_helper.rb'
    - 'app/helpers/patient_analysis_helper.rb'
    - 'app/helpers/records_helper.rb'
    - 'app/jobs/product_test_setup_job.rb'
    - 'app/models/checklist_source_data_criteria.rb'
    - 'app/models/test_execution.rb'
    - 'features/step_definitions/record.rb'
    - 'lib/cypress.rb'
    - 'lib/cypress/create_download_zip.rb'
    - 'lib/cypress/measure_evaluator.rb'
    - 'lib/cypress/npi_generator.rb'
    - 'lib/cypress/patient_zipper.rb'
    - 'lib/ext/bundle.rb'
    - 'test/controllers/vendor_records_controller_test.rb'
    - 'test/factories/measures.rb'
    - 'test/factories/value_sets.rb'
Style/StringLiterals:
  Exclude:
    - '.simplecov'
Style/WordArray:
  Exclude:
    - 'features/step_definitions/multi_measure_test.rb'
    - 'test/helpers/measure_helper_test.rb'
    - 'test/models/cms_program_task_test.rb'
    - 'test/models/multi_measure_cat1_task_test.rb'
    - 'test/models/multi_measure_cat3_task_test.rb'
    - 'test/models/multi_measure_test_test.rb'
    - 'test/unit/product_report_test.rb'
