scss_files: 'app/assets/stylesheets/**/*.scss'

exclude:
  - 'app/assets/stylesheets/_bootstrap-variables.scss'
  - 'app/assets/stylesheets/cypress/_xml_view.scss'
  - 'app/assets/stylesheets/cypress/_select2.scss'

linters:
  Comment:
    exclude: 'app/assets/stylesheets/application.scss'

  HexNotation:
    enabled: false

  EmptyLineBetweenBlocks:
    severity: error

  EmptyRules:
    severity: error

  IdSelector:
    severity: error

  NestingDepth:
    severity: error
    max_depth: 5

  PlaceholderInExtend:
    enabled: false

  SelectorDepth:
    severity: error
    max_depth: 5

  SelectorFormat:
    enabled: false

  PropertySortOrder:
    enabled: false

  VariableForProperty:
    enabled: true
    severity: error
    properties:
      - color
      - background-color

  VendorPrefix:
    enabled: true
    identifier_list:
      - base
