codecov:
  require_ci_to_pass: no
  token: 5b330fa7-3e02-484f-9a72-d5e22de4332b
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true