services:
  nginx:
    image: nginx:1.28-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - USE_SSL=true
    volumes:
      - ./docker/nginx:/docker/nginx:ro
      - ./docker/nginx/nginx-init.sh:/docker-entrypoint.d/nginx-init.sh:ro
  cypress:
    image: cypress:dev
    platform: linux/amd64
    build:
      context: .
      target: dev
    volumes:
      - cypress-vol:/app/public/data
      - ./docker/config:/docker/config
      - ./app:/app/app:ro
      - ./config:/app/config:ro
      - ./lib:/app/lib:ro  
    environment:
      - MONGO_PORT_27017_TCP_ADDR=mongodb
      - MONGO_PORT_27017_TCP_PORT=27017
      - CQM_EXECUTION_SERVICE_HOST=cqm-execution-service
      - SECRET_KEY_BASE=insecure_5131595823afbc3e6af90151ea8991fb3fc7d66e2a352f7664e6ef83bf572cfce8669ce542793b1597f3266706e4bc1ae3dee7f9b5023496ac21990
      - RAILS_ENV=development
  mongodb:
    image: mongo:8.0.9
    volumes:
      - mongo-data:/data/db
      - ./mongo:/etc/mongo
    command: --config=/etc/mongo/docker_mongod.conf
  cqm-execution-service:
    image: mitrehealthdocker/cqm-execution-service:cypress_v7
    platform: linux/amd64
volumes:
  cypress-vol:
  mongo-data:
