# frozen_string_literal: true

require_relative 'hash'
require_relative 'api'

require_relative '../app/uploaders/document_uploader'
require_relative '../app/uploaders/patient_archive_uploader'
require_relative '../app/uploaders/supplement_uploader'

require_relative 'cypress/error_collector'
require_relative 'cypress/product_status_values'
require_relative '../app/helpers/test_executions_results_helper'

require_relative '../app/helpers/application_helper'
require_relative '../app/helpers/checklist_tests_helper'
require_relative '../app/helpers/filtering_tests_helper'
require_relative '../app/helpers/measures_helper'
require_relative '../app/helpers/patient_analysis_helper'
require_relative '../app/helpers/products_helper'
require_relative '../app/helpers/qrda_helper'
require_relative '../app/helpers/records_helper'
require_relative '../app/helpers/test_executions_helper'
require_relative '../app/helpers/users_helper'
require_relative '../app/helpers/vendors_helper'
require_relative '../app/helpers/version_config_helper'
require_relative '../app/helpers/xml_view_helper'

require_relative 'ext/bundle'
require_relative 'ext/data_element'
require_relative 'ext/id'
require_relative 'ext/individual_result'
require_relative 'ext/measure'
require_relative 'ext/moped'
require_relative 'ext/patient'
require_relative 'ext/provider'
require_relative 'ext/string'
require_relative 'ext/value_set'
require_relative 'ext/zip_file_generator'

require_relative 'validators/validator'
require_relative 'validators/smoking_gun_validator'
require_relative 'validators/calculating_smoking_gun_validator'
require_relative 'validators/qrda_file_validator'
require_relative 'validators/calculating_augmented_records'
require_relative 'validators/calculating_augmented_results'
require_relative 'validators/cat3_population_validator'
require_relative 'validators/checklist_criteria_validator'
require_relative 'validators/cms_schematron_validator'
require_relative 'validators/core_clinical_data_element_validator'
require_relative 'validators/ehr_certification_id_validator'
require_relative 'validators/encounter_validator'
require_relative 'validators/expected_results_validator'
require_relative 'validators/expected_supplemental_results'
require_relative 'validators/measure_period_validator'
require_relative 'validators/program_criteria_validator'
require_relative 'validators/program_validator'
require_relative 'validators/provider_type_validator'
require_relative 'validators/qrda_cat1_validator'
require_relative 'validators/qrda_cat3_validator'
require_relative 'validators/qrda_upload_validator'

require_relative 'cypress/highlighting/highlighting'

require_relative 'cypress/api_measure_evaluator'
require_relative 'cypress/clinical_randomizer'
require_relative 'cypress/cql_bundle_importer'
require_relative 'cypress/cqm_execution_calc'
require_relative 'cypress/create_download_zip'
require_relative 'cypress/create_total_test_zip'
require_relative 'cypress/criteria_picker'
require_relative 'cypress/data_criteria_attribute_builder'
require_relative 'cypress/data_criteria_selector'
require_relative 'cypress/demographics_randomizer'
require_relative 'cypress/example_patient_finder'
require_relative 'cypress/expected_results_calculator'
require_relative 'cypress/mbi_generator'
require_relative 'cypress/measure_evaluator'
require_relative 'cypress/name_randomizer'
require_relative 'cypress/npi_generator'
require_relative 'cypress/patient_filter'
require_relative 'cypress/patient_zipper'
require_relative 'cypress/population_clone_job'
require_relative 'cypress/provider_filter'
require_relative 'cypress/qrda_post_processor'
require_relative 'cypress/scoop_and_filter'

require_relative '../app/models/vendor'
require_relative '../app/models/product'
require_relative '../app/models/product_test'
require_relative '../app/models/task'

require_relative '../app/models/ability'
require_relative '../app/models/artifact'
require_relative '../app/models/bundle_download'
require_relative '../app/models/c1_checklist_task'
require_relative '../app/models/c1_task'
require_relative '../app/models/c2_task'
require_relative '../app/models/c3_cat1_task'
require_relative '../app/models/c3_cat3_task'
require_relative '../app/models/c3_checklist_task'
require_relative '../app/models/cat1_filter_task'
require_relative '../app/models/cat3_filter_task'
require_relative '../app/models/checklist_source_data_criteria'
require_relative '../app/models/checklist_test'
require_relative '../app/models/cms_program_task'
require_relative '../app/models/cms_program_test'
require_relative '../app/models/execution_error'
require_relative '../app/models/filtering_test'
require_relative '../app/models/measure_test'
require_relative '../app/models/multi_measure_cat1_task'
require_relative '../app/models/multi_measure_cat3_task'
require_relative '../app/models/multi_measure_test'
require_relative '../app/models/point_of_contact'
require_relative '../app/models/program_criterion'
require_relative '../app/models/qrda_upload'
require_relative '../app/models/qrda_upload_task'
# require_relative '../app/models/role'
require_relative '../app/models/settings'
require_relative '../app/models/test_execution'
require_relative '../app/models/tracker'
# require_relative '../app/models/user'

require_relative '../app/lib/job/status'
require_relative '../app/jobs/application_job'
require_relative '../app/jobs/bundle_deprecate_job'
require_relative '../app/jobs/bundle_destroy_job'
require_relative '../app/jobs/bundle_upload_job'
require_relative '../app/jobs/checklist_test_setup_job'
require_relative '../app/jobs/cms_test_execution_job'
require_relative '../app/jobs/measure_evaluation_job'
require_relative '../app/jobs/mpl_download_create_job'
require_relative '../app/jobs/patient_analysis_job'
require_relative '../app/jobs/product_test_setup_job'
require_relative '../app/jobs/single_measure_calculation_job'
require_relative '../app/jobs/test_execution_job'
require_relative '../app/jobs/vendor_patient_upload_job'

# Dir["#{File.dirname(__FILE__)}/validators/*.rb"].sort.each { |file| require file }.each { |file| require file }
# Dir["#{File.dirname(__FILE__)}/cypress/*.rb"].sort.each { |file| require file }.each { |file| require file }
# Dir["#{File.dirname(__FILE__)}/cypress/highlighting/*.rb"].sort.each { |file| require file }.each { |file| require file }
# Dir["#{File.dirname(__FILE__)}/ext/*.rb"].sort.each { |file| require file }.each { |file| require file }
require_relative 'bootstrap_breadcrumbs_builder'
