# Number of Suppressed Errrors: 21
AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: { 
  except_methods: [
    'ApplicationController#after_sign_out_path_for',
    'ApplicationController#catch_not_found',
    'TypeNotFound#authorize_vendor',
    'AdminController#download_logs',

  ]
}
RemoveUnusedMethodsInHelpersCheck: { 
  except_methods: [
    'XmlViewHelper#data_to_doc',
    'VersionConfigHelper#config_for_version',
    'FilteringTestsHelper#generate_filter_patients',
    'TestExecutionsHelper#get_title_message',
    'MeasuresHelper#pick_measure_for_filtering_test',
    'MeasuresHelper#should_reload_measure_test?',
    'ProductsHelper#perform_c3_certification_during_measure_test_message',
    'ProductsHelper#all_records_for_product',
    'ApplicationHelper#mpl_id?'
  ]
}
RemoveUnusedMethodsInModelsCheck: { 
  except_methods: [
    'ProductTest#inherited',
    'MeasureTest#cat1_status',
    'MeasureTest#cat3_status',
    'ChecklistSourceDataCriteria#change_criteria',
    'ExecutionError#by_validation_type',
    'ExecutionError#submission_errors',
    'User#active_for_authentication?',
    'User#inactive_message'
  ]
}
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
