<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2012r2sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="xs fn">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<measureMap>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'C:/Users/rickg/workspaces-svn/ClientProjects/QRDATesting/measure-specific-schematron/measureMap.xsd'"/>
			<xsl:for-each select="data/measureIndexData">
				<measure>
					<name>
						<xsl:sequence select="fn:string(Name)"/>
					</name>
					<setId>
						<xsl:attribute name="root" select="fn:string(SetId)"/>
					</setId>
					<version>
						<versionNumber>
							<xsl:sequence select="xs:string(xs:integer(fn:string(Version)))"/>
						</versionNumber>
						<id>
							<xsl:attribute name="root" select="fn:string(Id)"/>
						</id>
					</version>
				</measure>
			</xsl:for-each>
		</measureMap>
	</xsl:template>
</xsl:stylesheet>
